### ISSUE TITLE
save user comments

### ISSUE THREAD

**Issue by jadedgnome** [nobodyme/reddit-fetch#12]
save user comments to .txt file.

**Comment by nobodyme** [comment]
That is already supposed to happen, what are you experiencing?

**Comment by jadedgnome** [comment]
> That is already supposed to happen, what are you experiencing?

 python .\fetch_comments.py -l https://www.reddit.com/user/beerforbrains
Connecting to reddit..
Downloading comments..
Traceback (most recent call last):
  File ".\fetch_comments.py", line 68, in <module>
    main()
  File ".\fetch_comments.py", line 50, in main
    top_level_comments = get_comments(
  File ".\fetch_comments.py", line 20, in get_comments
    title = data[0]['data']['children'][0]['data']['title']
KeyError: 0

**Comment by nobodyme** [comment]
Hey, the tool downloads the comments for a reddit post, it doesn't yet have the ability to fetch the comments under a user.
